# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 01:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devs_Time_Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.TimeField()),
                ('items_complete', models.IntegerField(blank=True, default=None, null=True)),
                ('dev_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.Projects')),
            ],
        ),
    ]
