# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_devs_time_reports_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devs_time_reports',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
