# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_auto_20170620_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devs_time_reports',
            name='time_spent',
            field=models.DurationField(),
        ),
    ]
